# This file is managed by `repo_helper`. Don't edit it directly
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'pypy3'

install:

  - pip install pip  --upgrade
  - pip install tox tox-travis
  - pip install coveralls

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda
  - deploy_releases

jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/flake8_strftime
        provider: pypi
        user: "DomDF"
        password:
          secure: EAbTEh6Bnb50yoQybiwf7WgQkRyyepwLT2r9ZqI4JDeowxXmHAcJhbjSCsJsgT8tGAhutmekcGH1+zQR4FPggFoBCiLjGT9zBbwvAzDe4yFQ+hcvMpDY6CmH5YUes2ih1xB51kt7FVcmAHmm9re2snIASLwKTYHuuWbRL85QCe/t1eSZ6bWv1xBVEL9QuraAU9V2zyfsjvi+EXsusXIAXZB8SDgzJkgUhm8zNoj5Nr1Uhy7DkW2ty0LVKy+WzE7PTT8A5Uwl247vPSxqo+U+BBlXfU4dkEzxlYka7oSXnkT6knBQkY09jKVg511jZUyLsA2lu+xgbJXqFsSgTe6UK74aSa9q8aWxUkxFdiKZUQldvwWfVJvNEJTVCw9/eFv4/U0FSN+zZYzZmd3hOEN/rxwV/UdChuRWnXrOdO2QJZSAi1S8lg1a8SdPa3vRAC/hr2qalIm77H+5AkdZsxGh1tUV+hTy8lfWeySftyzl+5KTnwjvnBHvKbQxA7OZ7A2FBoC9ynKVRIN6x2/rU3bqZNXfEV8Vq2MI6yPGrAWxquljltHKzChaLtxaVMmM9RKQUyD3XUNpSWABed3/IVjcDoE4xIf3kSzYisiKaNNEBBGHIqICX0z4sZQ5Fsxf+RPcRvYMhxYiT8V3pPUi9i4uF2E+sscALBaGGdgPiGsrPN0=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: domdfcoding/flake8_strftime
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;
